[project]
name = "expenses_manager"
version = "0.1.0"
description = "A small tool for expenses management"
dependencies = [
    "pymongo",
    "textual"
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

